name: Auto Assign
on:
  pull_request:
    types: [opened]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-assign@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          reviewers: |
            yoonlight
          assignees: yoonlight
          skipKeywords: wip, draft
