name: build and deploy
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
      - "develop"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      CI: true

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install and Build 🔧
        run: |
          cd frontend
          npm ci
          npm run build
      - name: copy file via ssh
        uses: appleboy/scp-action@master
        if: ${{ github.base_ref == 'develop' }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "frontend/dist/"
          target: ${{ secrets.DEV_PATH }}
          strip_components: 2
      - name: copy file via ssh
        uses: appleboy/scp-action@master
        if: ${{ github.base_ref == 'main' }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "frontend/dist/"
          target: ${{ secrets.PATH }}
          strip_components: 2