name: build and deploy
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
      - "develop"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      CI: false

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock
      - name: Install and Build 🔧
        run: |
          cd frontend
          yarn --prefer-offline
          yarn build
        env:
          VITE_KAKAO_KEY: ${{ secrets.VITE_KAKAO_KEY }}
          VITE_FB_API_KEY: ${{ secrets.VITE_FB_API_KEY }}
          VITE_FB_AUTH_DOMAIN: ${{ secrets.VITE_FB_AUTH_DOMAIN }}
          VITE_FB_PROJECT_ID: ${{ secrets.VITE_FB_PROJECT_ID }}
          VITE_FB_STORAGE_BUCKET: ${{ secrets.VITE_FB_STORAGE_BUCKET }}
          VITE_FB_MESSAGING_SENDER_ID: ${{ secrets.VITE_FB_MESSAGING_SENDER_ID }}
          VITE_FB_APP_ID: ${{ secrets.VITE_FB_APP_ID }}
          VITE_FB_MEASUREMENT_ID: ${{ secrets.VITE_FB_MEASUREMENT_ID }}
      - name: copy file via ssh
        uses: appleboy/scp-action@master
        if: ${{ github.base_ref == 'develop' }}
        with:
          host: ${{ secrets.WOODBLOCK_HOST }}
          username: ${{ secrets.WOODBLOCK_USERNAME }}
          password: ${{ secrets.WOODBLOCK_KEY }}
          port: ${{ secrets.WOODBLOCK_PORT }}
          source: "frontend/dist/"
          target: ${{ secrets.WOODBLOCK_DEV_PATH }}
          strip_components: 2
      - name: copy file via ssh
        uses: appleboy/scp-action@master
        if: ${{ github.base_ref == 'main' }}
        with:
          host: ${{ secrets.WOODBLOCK_HOST }}
          username: ${{ secrets.WOODBLOCK_USERNAME }}
          password: ${{ secrets.WOODBLOCK_KEY }}
          port: ${{ secrets.WOODBLOCK_PORT }}
          source: "frontend/dist/"
          target: ${{ secrets.WOODBLOCK_PATH }}
          strip_components: 2